Docs: Update README.md
The-OpenROAD-Project/ORAssistant pull request #22
Opened 2024-07-03 13:20 UTC by luarss

Improve clarity in set up for top-level readme.

2024-07-05 00:14 UTC, dralabeing requested changes
@luarss Can you list the separate functions handled by the front-end and back-end ? This gives a clear understanding of the workflow for each part.

2024-07-09 13:33 UTC, vvbandeira commented on README.md
> +- Frontend: We use Streamlit to communicate with a chat endpoint, provides a user-friendly chat interface.
```suggestion
- Frontend: We use Streamlit to communicate with a chat endpoint, providing a user-friendly chat interface.
```

2024-07-09 14:50 UTC, vvbandeira approved these changes

2024-07-09 14:52 UTC, vvbandeira commented
@dralabeing 
Your approval is required for the merge since you requested changes.

2024-07-09 18:17 UTC, dralabeing approved these changes

2024-07-10 01:18 UTC, merged